import { afterAll, beforeAll, expect, test, vi } from 'vitest';
const session=vi.hoisted(()=>({id:null as number|null}));
vi.mock('next-auth',()=>({getServerSession:async()=>session.id===null?null:{user:{id:session.id}}}));
vi.mock('@/app/api/auth/[...nextauth]/route',()=>({authOptions:{}}));
import { prisma } from '@/lib/prisma';
import { defaultSettings } from '@/lib/discord/config';
import { GET as configGet, PUT as configPut } from '@/app/api/discord/config/route';
import { PATCH as retentionPatch } from '@/app/api/discord/retention/route';
import { POST as heartbeat } from '@/app/api/discord/heartbeat/route';
import { POST as queue } from '@/app/api/discord/commands/route';
import { POST as claim } from '@/app/api/discord/commands/claim/route';
import { POST as complete } from '@/app/api/discord/commands/[id]/complete/route';
import { POST as caseCreate } from '@/app/api/discord/cases/route';
import { POST as evidenceCreate, GET as evidenceList } from '@/app/api/discord/evidence/route';
import { PATCH as evidenceAction } from '@/app/api/discord/evidence/[id]/route';
import { PATCH as memberName } from '@/app/api/discord/members/[discordId]/name/route';
import { POST as signupCreate, DELETE as signupDelete, PATCH as signupMove } from '@/app/api/discord/members/[discordId]/orbats/[id]/signup/route';
import { PATCH as memberAvailability } from '@/app/api/discord/members/[discordId]/orbats/[id]/availability/route';
import { PATCH as websiteProfile } from '@/app/api/users/[id]/route';
import { maintainDiscordEvidence, RECOVERY_MS } from '@/lib/discord/evidence-maintenance';
let admin:number,member:number;
const guild='990000000000000001',discordId='990000000000000002',channel='990000000000000003',role='990000000000000004';
const req=(path:string,method='GET',body?:unknown,bot=false,key?:string)=>new Request(`http://localhost/api/discord/${path}`,{method,headers:{...(bot?{authorization:'Bearer discord-admin-integration'}:{}),...(key?{'Idempotency-Key':key}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
const ctx=(id:number)=>({params:Promise.resolve({id:String(id)})});
const mc=(orbatId:number)=>({params:Promise.resolve({id:String(orbatId),discordId})});
beforeAll(async()=>{
  const permission=await prisma.permission.upsert({where:{key:'system:super_admin'},create:{key:'system:super_admin'},update:{}});
  admin=(await prisma.user.create({data:{username:'Discord admin integration',userPermissions:{create:{permissionId:permission.id,value:1}}}})).id;
  member=(await prisma.user.create({data:{username:'Discord member integration',accounts:{create:{provider:'discord',providerUserId:discordId}}}})).id;
  await prisma.botToken.create({data:{name:'Discord integration',token:'discord-admin-integration'}});
  session.id=admin;
});
afterAll(async()=>{await prisma.$disconnect();});
test('configuration revisions and bot acknowledgement remain separate, and revoked configuration access is denied',async()=>{
  const first=await (await configGet(req('config'))).json(); expect(first.data.revision).toBe(0);
  const settings={...defaultSettings(),guildId:guild,websiteUrl:'https://unit.example',welcomeChannelId:channel,nicknameSync:true,honeypotEnabled:true,honeypotChannelId:channel,staffLogChannelId:channel,membershipRoleIds:[role]};
  expect((await configPut(req('config','PUT',{revision:0,settings}))).status).toBe(200);
  expect((await configPut(req('config','PUT',{revision:0,settings}))).status).toBe(409);
  expect((await heartbeat(req('heartbeat','POST',{guildId:guild,appliedRevision:1,botVersion:'test',health:'healthy',metadata:{roles:[],channels:[]}},true))).status).toBe(200);
  const state=await (await configGet(req('config'))).json();expect(state.data).toMatchObject({revision:1,appliedRevision:1,health:'healthy'});
  session.id=member;expect((await configPut(req('config','PUT',{revision:1,settings}))).status).toBe(403);session.id=admin;
});
test('commands persist claims and acknowledgements, reject stale tokens, and replay terminal results safely',async()=>{
  const queued=await (await queue(req('commands','POST',{requestKey:'integration-command-1',kind:'welcome.test',payload:{}}))).json();expect(queued.data.status).toBe('pending');
  const claimed=await (await claim(req('commands/claim','POST',{},true))).json();expect(claimed.data.status).toBe('running');
  const result={claimToken:claimed.data.claimToken,generation:claimed.data.generation,success:true,result:{}};
  expect((await complete(req('complete','POST',{...result,claimToken:'stale'},true),ctx(queued.data.id))).status).toBe(409);
  expect((await complete(req('complete','POST',result,true),ctx(queued.data.id))).status).toBe(200);
  expect((await complete(req('complete','POST',result,true),ctx(queued.data.id))).status).toBe(200);
  expect(await prisma.discordCommand.count({where:{requestKey:'integration-command-1'}})).toBe(1);
});
test('evidence captures bytes, automatic expiry is recoverable, restore and indefinite marking protect against purge, manual purge removes bytes',async()=>{
  const now=new Date();
  const created=await (await caseCreate(req('cases','POST',{triggerId:'990000000000000010',guildId:guild,memberId:discordId,roleIds:[],configRevision:1,occurredAt:now.toISOString()},true))).json();expect(created.data.action).toBe('ban');
  const upload={caseId:created.data.id,messageId:'990000000000000011',channelId:channel,authorId:discordId,sentAt:now.toISOString(),content:'evidence text',attachments:[{name:'proof.txt',contentType:'text/plain',dataBase64:Buffer.from('proof').toString('base64')}]};
  const response=await evidenceCreate(req('evidence','POST',upload,true));expect(response.status).toBe(201);expect((await evidenceCreate(req('evidence','POST',upload,true))).status).toBe(201);const saved=(await response.json()).data;
  const original=await prisma.discordEvidence.findUniqueOrThrow({where:{id:saved.id}});
  const expiry=new Date(original.expiresAt!.getTime()+1);await maintainDiscordEvidence(expiry);
  let row=await prisma.discordEvidence.findUniqueOrThrow({where:{id:saved.id}});expect(row.content).toBe('evidence text');expect(row.deletedAt).toEqual(expiry);expect(row.recoverUntil!.getTime()-expiry.getTime()).toBe(RECOVERY_MS);
  expect((await evidenceAction(req('evidence','PATCH',{version:row.version,action:'restore'}),ctx(row.id))).status).toBe(200);
  row=await prisma.discordEvidence.findUniqueOrThrow({where:{id:row.id}});
  expect((await evidenceAction(req('evidence','PATCH',{version:row.version,action:'indefinite'}),ctx(row.id))).status).toBe(200);
  await maintainDiscordEvidence(new Date(expiry.getTime()+2*RECOVERY_MS));row=await prisma.discordEvidence.findUniqueOrThrow({where:{id:row.id}});expect(row.purgedAt).toBeNull();expect(row.indefinite).toBe(true);
  session.id=member;expect((await evidenceList(req('evidence'))).status).toBe(403);session.id=admin;
  const deleted=await evidenceAction(req('evidence','PATCH',{version:row.version,action:'delete'}),ctx(row.id));expect(deleted.status).toBe(200);
  row=await prisma.discordEvidence.findUniqueOrThrow({where:{id:row.id}});
  await maintainDiscordEvidence(row.recoverUntil!);const purged=await prisma.discordEvidence.findUniqueOrThrow({where:{id:row.id}});expect(purged.content).toBeNull();expect(purged.attachments).toBeNull();expect(purged.purgedAt).not.toBeNull();
  expect((await evidenceCreate(req('evidence','POST',upload,true))).status).toBe(409);
});
test('retention reductions leave existing expiry intact and indefinite extensions persist',async()=>{
  const revision=(await (await configGet(req('config'))).json()).data.revision;
  expect((await retentionPatch(req('retention','PATCH',{revision,retention:{mode:'days',days:30}}))).status).toBe(200);
  const mc=await prisma.discordModerationCase.findFirstOrThrow();
  const item=await prisma.discordEvidence.create({data:{caseId:mc.id,messageId:'990000000000000019',channelId:channel,authorId:discordId,sentAt:new Date(),content:'keep',expiresAt:new Date(Date.now()+30*86400000)}});
  expect((await retentionPatch(req('retention','PATCH',{revision:revision+1,retention:{mode:'days',days:7}}))).status).toBe(200);
  expect((await prisma.discordEvidence.findUniqueOrThrow({where:{id:item.id}})).expiresAt).toEqual(item.expiresAt);
});
test('website and Discord name updates share compare-and-set revision without storing rank prefix',async()=>{
  session.id=member;
  expect((await websiteProfile(new Request('http://localhost/api/users/me',{method:'PATCH',body:JSON.stringify({username:'Website name'})}),ctx(member))).status).toBe(200);session.id=admin;
  expect((await memberName(req('name','PATCH',{nameRevision:0,username:'Stale name'},true),{params:Promise.resolve({discordId})})).status).toBe(409);
  expect((await memberName(req('name','PATCH',{nameRevision:1,username:'Moderator correction',actorDiscordId:guild},true),{params:Promise.resolve({discordId})})).status).toBe(200);
  expect((await prisma.user.findUniqueOrThrow({where:{id:member}})).nameRevision).toBe(2);
});
test('member interactions enforce capacity, ownership, signup cancellation replay and availability cutoff despite bot superadmin',async()=>{
  const orbat=await prisma.orbat.create({data:{name:'Discord integration operation',createdById:admin,startsAtUtc:new Date(Date.now()+86400000),endsAtUtc:new Date(Date.now()+90000000)}});
  const squad=await prisma.squad.create({data:{name:'Discord squad',orbatId:orbat.id,orderIndex:0}});
  const slot=await prisma.slot.create({data:{orbatId:orbat.id,squadId:squad.id,orderIndex:0,maxSignups:1}});
  const create=await signupCreate(req('signup','POST',{slotId:slot.id},true,'discord-signup-1'),mc(orbat.id));expect(create.status).toBe(201);const signup=(await create.json()).data;
  const second=await prisma.slot.create({data:{orbatId:orbat.id,squadId:squad.id,orderIndex:1,maxSignups:1}});
  expect((await signupMove(req('signup','PATCH',{signupId:signup.id,slotId:second.id},true,'discord-move-1'),mc(orbat.id))).status).toBe(200);
  const del=()=>signupDelete(req('signup','DELETE',{signupId:signup.id},true,'discord-cancel-1'),mc(orbat.id));expect((await del()).status).toBe(200);expect((await del()).status).toBe(200);
  await prisma.orbat.update({where:{id:orbat.id},data:{startsAtUtc:new Date(Date.now()-90000000),endsAtUtc:new Date(Date.now()-86400000)}});
  expect((await memberAvailability(req('availability','PATCH',{status:'absent'},true),mc(orbat.id))).status).toBe(409);
});
