import { test, expect } from './fixtures';

test('training categories can be created, renamed and deleted without deleting their trainings', async ({ page, login, db }) => {
  await login();
  await page.goto('/admin/trainings');
  await page.getByRole('button', { name: /^Categories \(/ }).click();
  await page.getByPlaceholder('e.g., Combat, Medical, Aviation...').fill('Workflow Medical');
  await page.getByRole('button', { name: 'Add Category', exact: true }).click();
  const card = page.locator('div.p-4.rounded-lg').filter({ has: page.getByRole('heading', { name: 'Workflow Medical', exact: true }) });
  await expect(card).toBeVisible();
  const category = await db.trainingCategory.findUniqueOrThrow({ where: { name: 'Workflow Medical' } });
  const training = await db.training.create({ data: { name: 'Workflow Category Training', categoryId: category.id } });
  await card.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.locator('input[value="Workflow Medical"]').fill('Workflow Advanced Medical');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  const updated = page.locator('div.p-4.rounded-lg').filter({ has: page.getByRole('heading', { name: 'Workflow Advanced Medical', exact: true }) });
  await expect(updated).toBeVisible();
  await updated.getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Delete Category', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Delete', exact: true }).last().click();
  await expect(updated).toHaveCount(0);
  expect(await db.trainingCategory.count({ where: { id: category.id } })).toBe(0);
  expect((await db.training.findUniqueOrThrow({ where: { id: training.id } })).categoryId).toBeNull();
});

test('staff approve a request, assign its session and record a practical qualification', async ({ page, login, db, seed }) => {
  const training = await db.training.create({ data: { name: 'Workflow Request Lifecycle', requiresTrainingSession: true, requiresOrbatQualification: true } });
  const request = await db.trainingRequest.create({ data: { trainingId: training.id, userId: seed.memberId } });
  const session = await db.trainingSession.create({ data: { trainingId: training.id, trainerId: seed.adminId, createdById: seed.adminId, startsAt: new Date('2099-10-10T17:00:00Z'), durationMinutes: 60, status: 'scheduled' } });
  await login();
  await page.goto(`/trainings/requests/${request.id}`);
  await page.getByLabel('Notes or feedback').fill('Approved by browser workflow');
  await page.getByRole('button', { name: /^Approve Request/ }).click();
  await expect(page.getByRole('button', { name: /^Start Training/ })).toBeVisible();
  await page.getByLabel('Assign an already scheduled session').selectOption(String(session.id));
  await page.getByRole('button', { name: 'Assign Session', exact: true }).click();
  await expect.poll(async () => (await db.trainingSessionAttendee.findUnique({ where: { trainingRequestId: request.id } }))?.sessionId).toBe(session.id);
  await page.getByRole('button', { name: /^Start Training/ }).click();
  await expect(page.getByRole('button', { name: /^Session Passed/ })).toBeVisible();
  await page.getByRole('button', { name: /^Session Passed/ }).click();
  await expect(page.getByRole('button', { name: /^Mark Qualified/ })).toBeVisible();
  await page.getByLabel('Notes or feedback').fill('Practical assessment passed');
  await page.getByRole('button', { name: /^Mark Qualified/ }).click();
  await expect(page.getByRole('button', { name: /^Start New Qualification Attempt/ })).toBeVisible();
  expect((await db.trainingRequest.findUniqueOrThrow({ where: { id: request.id } })).status).toBe('qualified');
  expect((await db.userTraining.findUniqueOrThrow({ where: { userId_trainingId: { userId: seed.memberId, trainingId: training.id } } })).status).toBe('qualified');
  await page.reload();
  await expect(page.getByRole('button', { name: /^Start New Qualification Attempt/ })).toBeVisible();
});

test('session management persists schedule edits, attendee attendance and cancellation', async ({ page, login, db, seed }) => {
  const training = await db.training.create({ data: { name: 'Workflow Session Administration', requiresTrainingSession: true } });
  const session = await db.trainingSession.create({ data: { trainingId: training.id, trainerId: seed.adminId, createdById: seed.adminId, startsAt: new Date('2099-11-10T17:00:00Z'), durationMinutes: 60, status: 'scheduled' } });
  await login();
  await page.goto('/admin/trainings');
  await page.getByRole('button', { name: 'Sessions', exact: true }).click();
  const card = page.locator(`#training-session-${session.id}`);
  await card.getByRole('button', { name: 'Manage', exact: true }).click();
  await card.getByLabel('Duration (minutes)', { exact: true }).fill('90');
  await card.getByLabel('Special instructions', { exact: true }).fill('Bring navigation equipment');
  await card.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect.poll(async () => (await db.trainingSession.findUniqueOrThrow({ where: { id: session.id } })).durationMinutes).toBe(90);
  await card.getByLabel('User to add to training session').selectOption(`user:${seed.memberId}`);
  await card.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(card.getByLabel('Attendance status for Browser Member')).toBeVisible();
  await card.getByLabel('Attendance status for Browser Member').selectOption('attended');
  await card.getByPlaceholder('Attendance notes').fill('Present for instruction');
  await card.getByRole('button', { name: 'Save', exact: true }).click();
  await expect.poll(async () => (await db.trainingSessionAttendee.findUnique({ where: { sessionId_userId: { sessionId: session.id, userId: seed.memberId } } }))?.status).toBe('attended');
  await card.getByRole('combobox', { name: 'Status', exact: true }).selectOption('cancelled');
  page.once('dialog', dialog => dialog.accept());
  await card.getByRole('button', { name: 'Cancel session', exact: true }).click();
  await expect(card.getByText('This session is final and can no longer be edited.')).toBeVisible();
  expect((await db.trainingSession.findUniqueOrThrow({ where: { id: session.id } })).status).toBe('cancelled');
});

test('qualification management records failed attempts and successful reassessment with history', async ({ page, login, db, seed }) => {
  const training = await db.training.create({ data: { name: 'Workflow Qualification Review', requiresTrainingSession: false, requiresOrbatQualification: true } });
  const record = await db.userTraining.create({ data: { userId: seed.memberId, trainingId: training.id, status: 'needs_qualify' } });
  await login();
  await page.goto('/admin/trainings');
  await page.getByRole('button', { name: 'Qualifications', exact: true }).click();
  const card = page.locator('article').filter({ hasText: training.name });
  await expect(card).toBeVisible();
  await card.getByPlaceholder('Optional notes saved with the next status change').fill('Repeat the practical assessment');
  page.once('dialog', dialog => dialog.accept());
  await card.getByRole('button', { name: 'Failed', exact: true }).click();
  await expect(card.getByRole('button', { name: 'Needs qualification', exact: true })).toBeVisible();
  expect((await db.userTraining.findUniqueOrThrow({ where: { id: record.id } })).status).toBe('failed');
  await card.getByRole('button', { name: 'Needs qualification', exact: true }).click();
  await expect(card.getByRole('button', { name: 'Qualified', exact: true })).toBeVisible();
  await card.getByRole('button', { name: 'Qualified', exact: true }).click();
  await expect.poll(async () => (await db.userTraining.findUniqueOrThrow({ where: { id: record.id } })).status).toBe('qualified');
  const history = await db.userTrainingStatusHistory.findMany({ where: { userTrainingId: record.id }, orderBy: { id: 'asc' } });
  expect(history.map(item => item.toStatus)).toEqual(['failed', 'needs_qualify', 'qualified']);
  await page.reload();
  await page.getByRole('button', { name: 'Qualifications', exact: true }).click();
  await expect(card.getByRole('button', { name: 'Needs qualification', exact: true })).toBeVisible();
});

test('staff create and confirm a new UTC training schedule from a request', async ({ page, login, db, seed }) => {
  const training = await db.training.create({ data: { name: 'Workflow New Schedule', requiresTrainingSession: true, duration: 60 } });
  const request = await db.trainingRequest.create({ data: { trainingId: training.id, userId: seed.memberId, status: 'approved' } });
  await login();
  await page.goto(`/trainings/requests/${request.id}`);
  await page.getByLabel('Assigned trainer', { exact: true }).selectOption(String(seed.adminId));
  await page.getByLabel('Date (UTC)', { exact: true }).fill('2099-10-12');
  await page.getByLabel('Time (UTC)', { exact: true }).click();
  const dial = page.getByRole('group', { name: 'Time (UTC) clock picker' });
  await dial.click({ position: { x: 240, y: 132 } });
  await dial.click({ position: { x: 132, y: 24 } });
  await page.getByLabel('Duration (minutes)', { exact: true }).fill('75');
  await page.getByLabel('Special instructions', { exact: true }).fill('Meet on the training server');
  await page.getByRole('button', { name: 'Assign & Confirm', exact: true }).click();
  await expect.poll(async () => db.trainingSessionAttendee.count({ where: { trainingRequestId: request.id } })).toBe(1);
  const attendee = await db.trainingSessionAttendee.findUniqueOrThrow({ where: { trainingRequestId: request.id }, include: { session: true } });
  expect(attendee.session.status).toBe('scheduled');
  expect(attendee.session.startsAt?.toISOString()).toBe('2099-10-12T15:00:00.000Z');
  expect(attendee.session.durationMinutes).toBe(75);
  expect(attendee.session.trainerId).toBe(seed.adminId);
  await page.reload();
  await expect(page.getByLabel('Date (UTC)', { exact: true })).toHaveValue('2099-10-12');
  await expect(page.getByLabel('Special instructions', { exact: true })).toHaveValue('Meet on the training server');
});
