import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./components/layout/TopBar";
import AuthSessionProvider from "./components/layout/SessionProvider";
import PermissionSessionSync from './components/layout/PermissionSessionSync';
import { ToastProvider } from "./components/ui/ToastContainer";
import LinkAccountPrompt from "./components/auth/LinkAccountPrompt";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider>
          <ToastProvider>
            <PermissionSessionSync />
            <TopBar />
            {children}
            <LinkAccountPrompt />
          </ToastProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
